name: deploy to aabeling.github.io/mastermind/

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - name: deploy
        run: ng deploy --base-href=/mastermind/
        
