name: deploy to aabeling.github.io/mastermind/

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm install -g @angular/cli > /dev/null
      - run: ng deploy --base-href=/mastermind/
