name: deploy to aabeling.github.io/mastermind/

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm install -g @angular/cli > /dev/null
      - run: ng build --prod --output-path=dist --base-href="https://techiediaries.github.io/angular-bootstrap-demo/"
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: mastermind
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

